### ISSUE TITLE
did you modify caffe_ros to work, or concentrate on stereoDNN

### ISSUE THREAD

**Issue by vxgu86** [mtbsteve/redtail#3]
hi,bro

did you modify caffe_ros to work, or concentrate on stereoDNN
cause my caffe_ros did not work by showing this:

[ INFO] [1570795286.477613985]: Hardware support of fast FP16: yes.
[ INFO] [1570795286.477717602]: Hardware support of fast INT8: no.
[ INFO] [1570795286.477766363]: Using FP16 model data type.
[ INFO] [1570795286.477865292]: [TensorRT] CaffeParser: Could not open file 
[ INFO] [1570795286.477977245]: [TensorRT] CaffeParser: Could not parse model file
[FATAL] [1570795286.478039290]: Failed to parse network: , 
Segmentation fault (core dumped)

**Comment by vxgu86** [comment]
by the way, it's same for trailDNN and yolo model.

**Comment by mtbsteve** [comment]
I have not touched yet the caffe_ros node and without modifying the launch scripts neither Yolo nor Trailnet will work. Likely you will also need to make some changes for TRT5 support in the code. 
I am currently working on joystick support and the gscam video pipeline. stereoDNN in the meantime works for all models except resnet18 (which is not an issue since resnet18 would not run fast enough on a TX2 anyway). 
Jetpack 4.2 introduced a lot of changes which are incompatible with the original Redtail code. 
If you have any solutions ready please let me know and send a PR.

**Comment by mtbsteve** [comment]
@vxgu86 trailnet and yolo should work now.
`roslaunch caffe_ros ap_zed_gscam_trailnet_yolo_robot.launch`
Check with:
```
rostopic echo /trails_dnn/network/output
rostopic echo /object_dnn/network/output
rviz -d /home/apsync/redtail/ros/packages/redtail_debug/rviz/ap.rviz
```
